name: fquery
description: A flutter library to manage async state in your flutter apps.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  fast_immutable_collections: ^7.4.1
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
