name: fquery
description: fquery is a powerful async state management solution for Flutter. It caches, updates, and fully manages asynchronous data in your Flutter apps.
version: 1.2.0-beta.1
repository: https://github.com/41y08h/fquery

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  fast_immutable_collections: ^10.2.2
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
