name: fquery
description: FQuery is a powerful async state management solution for Flutter. It caches, updates and fully manages asynchronous data in your Flutter apps.
version: 1.0.0-beta.4
repository: https://github.com/41y08h/fquery

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
