name: fquery
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
